#===========================
# 容器相关设置
server:
  port: 8063
  compression:
    enabled: true  #是否开启压缩，默认为false.
    mime-types: 'application/json,text/css,text/html'   #指定要压缩的MIME type，多个以逗号分隔
    min-response-size: 2048  #执行压缩的阈值，默认为2048
debug: false
#log4j2相关配置
logging:
  config: classpath:log4j2-spring.xml
#============================
# spring 组件相关设置
spring:
  application:
    name: spring-authorization-server
  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
  boot:
    admin:
      client:
        url: 'http://localhost:8013'  # 添加spring boot admin监控  Spring Boot Admin Server的URL
        username: admin
        password: admin
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848    #nacos注册中心地址
management:
  endpoints:
    web:
      exposure:
        include: "*"  # 放开所有端点
  endpoint:
    health:
      show-details: ALWAYS
#=============================