#===========================
# 容器相关设置
server:
  port: 7081
debug: false
#log4j2相关配置
logging:
  config: classpath:log4j2-spring.xml
#============================
# spring 组件相关设置
spring:
  application:
    name: spring-authorization-server
  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
  boot:
    admin:
      client:
        url: 'http://localhost:1081'  # 添加spring boot admin监控  Spring Boot Admin Server的URL
        username: admin
        password: admin
management:
  endpoints:
    web:
      exposure:
        include: "*"  # 放开所有端点
  endpoint:
    health:
      show-details: ALWAYS
#=============================