#===========================
# 容器相关设置
server:
  port: 8092
debug: false
#log4j2相关配置
logging:
  config: classpath:log4j2-spring.xml
#============================
# spring 组件相关设置
spring:
  application:
    name: spring-nacos-sentinel
  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
  mvc:
    throw-exception-if-no-handler-found: true #告诉 SpringBoot 当出现 404 错误时, 直接抛出异常
  resources:
    add-mappings: false #告诉 SpringBoot 不要为我们工程中的资源文件建立映射
  boot:
    admin:
      client:
        url: http://localhost:8011  # 添加spring boot admin监控  Spring Boot Admin Server的URL
        username: admin
        password: admin   #监控中心服务端的用户名和密码
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848    #nacos注册中心地址
    sentinel:
      transport:
        dashboard: localhost:9090  #sentinel 工作台地址
        port: 8719       #默认8719端口 假如被占用会从8719开始依次加1扫描直到找到未被占用端口
      eager: true #取消Sentinel控制台懒加载
      # 配置Sentinel 数据源  进行规则持久化
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}-flow
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow   #流控规则
        ds2:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}-degrade
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: degrade   #降级规则
        ds3:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}-system
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: system   #系统规则
        ds4:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}-authority
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: authority   #授权规则
        ds5:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}-param
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: param_flow   #热点规则
management:
  endpoints:
    web:
      exposure:
        include: "*"  # 放开所有端点
  endpoint:
    health:
      show-details: ALWAYS
