#===========================
# 容器相关设置
server:
  port: 9052
debug: false
#log4j2相关配置
logging:
  config: classpath:log4j2-spring.xml
#============================
# spring 组件相关设置
spring:
  application:
    name: spring-boot-elasticsearch
  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
  mvc:
    throw-exception-if-no-handler-found: true #告诉 SpringBoot 当出现 404 错误时, 直接抛出异常
  resources:
    add-mappings: false #告诉 SpringBoot 不要为我们工程中的资源文件建立映射
elasticsearch:
  url: localhost
  port: 9200