#===========================
# 容器相关设置
server:
  port: 8031
debug: false
#log4j2相关配置
logging:
  config: classpath:log4j2-spring.xml
#============================
# spring 组件相关设置
spring:
  application:
    name: spring-api-common
  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
  boot:
    admin:
      client:
        url: http://localhost:8011  # 添加spring boot admin监控  Spring Boot Admin Server的URL
        username: admin
        password: admin
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848    #nacos注册中心地址
management:
  endpoints:
    web:
      exposure:
        include: "*"  # 放开所有端点
  endpoint:
    health:
      show-details: ALWAYS
#=============================