#===========================
# 容器相关设置
server:
  port: 9081
#log4j2相关配置
logging:
  config: classpath:log4j2-spring.xml
#============================
# spring 组件相关设置
spring:
  application:
    name: spring-api-common
  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
  rabbitmq:
    addresses: localhost
    port: 5672
    username: guest
    password: guest
#=============================

#=============================
#swagger
swagger:
  enabled: true
  title: 'swagger-spring-boot-starter'
  description: '基于Swagger构建的SpringBoot RESTApi 文档'
  version: '1.0'
  base-package: 'com.spring.boot'
  base-path: /**
  exclude-path:
#=============================